/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngthtrong.theatermanager.views;

import java.awt.Color;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import ngthtrong.theatermanager.controller.HomePageController;
import ngthtrong.theatermanager.controller.MovieController;
import ngthtrong.theatermanager.models.Movie;
import ngthtrong.theatermanager.models.Period;

/**
 *
 * @author jhiny
 */
public class MovieDetailForm extends javax.swing.JFrame {

    /**
     * Creates new form MovieFrom
     */
    public MovieDetailForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1000, 630);
    getContentPane().setBackground(Color.getHSBColor(0.2f, 0.05f, 0.95f));
}

    public void FormLoad() {
        this.setVisible(true);
        setEnable(false);
    }

    public void FormClose() {
        this.setVisible(false);
    }

    public void Cancel() {
        btnEdit.setEnabled(true);
        btnSaveChange.setEnabled(false);
        setEnable(false);
    }

    public void setEnable(boolean enable) {
        txtDescription.setEnabled(enable);
        txtMovieName.setEnabled(enable);
        commingFalse.setEnabled(enable);
        commingTrue.setEnabled(enable);
    }

    public void SetBtnDeleteEnable(boolean enable) {
        btnDeletePeriod.setEnabled(enable);
    }

    public void SetDetailMovie(Movie movie) {
        txtMovieID.setText(String.valueOf(movie.getMovie_id()));
        txtMovieName.setText(movie.getMovie_name());
        txtDescription.setText(movie.getDescription());
        onShowingTrue.setSelected(movie.isOnShowing());
        onShowingFalse.setSelected(!movie.isOnShowing());
        commingTrue.setSelected(movie.isCommingSoon());
        commingFalse.setSelected(!movie.isCommingSoon());
        if (movie.isOnShowing() == true) {
            commingTrue.setEnabled(false);
            commingFalse.setEnabled(false);
        } else {
            commingTrue.setEnabled(true);
            commingFalse.setEnabled(true);
        }
        lbOfTables.setText("List period of movie: " + movie.getMovie_name());
    }

    public void SetPeriods(List<Period> periods) {
        if (periods == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tbPeriods.getModel();
        model.setRowCount(0);
        for (Period period : periods) {
            model.addRow(
                    new Object[]{String.valueOf(period.getPeriod_id()), period.getMovie_name(),
                        period.getTheater_name(), String.valueOf(period.getPeriod_size()),
                        period.getPeriod_time(), period.getPeriod_date()});
        }
        tbPeriods.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrOnShow = new javax.swing.ButtonGroup();
        btnGrCommingSoon = new javax.swing.ButtonGroup();
        btnMovieForm = new javax.swing.JButton();
        lbMovieID = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        lbMovieID1 = new javax.swing.JLabel();
        txtMovieName = new javax.swing.JTextField();
        lbMovieDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnSaveChange = new javax.swing.JButton();
        btnDeletePeriod = new javax.swing.JButton();
        btnCreatePeriod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPeriods = new javax.swing.JTable();
        onShowingTrue = new javax.swing.JRadioButton();
        onShowingFalse = new javax.swing.JRadioButton();
        lbOnShowing = new javax.swing.JLabel();
        lbMovieID3 = new javax.swing.JLabel();
        commingTrue = new javax.swing.JRadioButton();
        commingFalse = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbOfTables = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        btnMovieForm.setBackground(new java.awt.Color(204, 0, 0));
        btnMovieForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMovieForm.setForeground(new java.awt.Color(255, 255, 255));
        btnMovieForm.setText("Movie");
        btnMovieForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieFormActionPerformed(evt);
            }
        });

        lbMovieID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID.setText("Movie ID:");

        txtMovieID.setEnabled(false);
        txtMovieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieIDActionPerformed(evt);
            }
        });
        txtMovieID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovieIDKeyReleased(evt);
            }
        });

        lbMovieID1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID1.setText("Name:");

        txtMovieName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovieNameKeyTyped(evt);
            }
        });

        lbMovieDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescription);

        btnEdit.setBackground(new java.awt.Color(180, 10, 10));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSaveChange.setBackground(new java.awt.Color(180, 10, 10));
        btnSaveChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveChange.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveChange.setText("Save change");
        btnSaveChange.setEnabled(false);
        btnSaveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangeActionPerformed(evt);
            }
        });

        btnDeletePeriod.setBackground(new java.awt.Color(180, 10, 10));
        btnDeletePeriod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletePeriod.setText("Delete Period");
        btnDeletePeriod.setEnabled(false);
        btnDeletePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeriodActionPerformed(evt);
            }
        });

        btnCreatePeriod.setBackground(new java.awt.Color(180, 10, 10));
        btnCreatePeriod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreatePeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePeriod.setText("Add Period");
        btnCreatePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePeriodActionPerformed(evt);
            }
        });

        tbPeriods.setBackground(new java.awt.Color(255, 225, 225));
        tbPeriods.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPeriods.setForeground(new java.awt.Color(40, 0, 0));
        tbPeriods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Period ID", "Movie Name", "Theater", "Booked", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPeriods.setGridColor(new java.awt.Color(255, 150, 150));
        tbPeriods.setRowHeight(30);
        jScrollPane2.setViewportView(tbPeriods);
        if (tbPeriods.getColumnModel().getColumnCount() > 0) {
            tbPeriods.getColumnModel().getColumn(0).setResizable(false);
            tbPeriods.getColumnModel().getColumn(1).setResizable(false);
            tbPeriods.getColumnModel().getColumn(2).setResizable(false);
            tbPeriods.getColumnModel().getColumn(3).setResizable(false);
            tbPeriods.getColumnModel().getColumn(4).setResizable(false);
        }

        btnGrOnShow.add(onShowingTrue);
        onShowingTrue.setText("Yes");
        onShowingTrue.setEnabled(false);

        btnGrOnShow.add(onShowingFalse);
        onShowingFalse.setText("No");
        onShowingFalse.setEnabled(false);

        lbOnShowing.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbOnShowing.setText("Now Showing:");

        lbMovieID3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID3.setText("Comming Soon:");

        btnGrCommingSoon.add(commingTrue);
        commingTrue.setText("Yes");

        btnGrCommingSoon.add(commingFalse);
        commingFalse.setText("No");

        btnBack.setBackground(new java.awt.Color(180, 10, 10));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(180, 10, 10));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbOfTables.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbOfTables.setText("List period of movie:");

        btnHome.setBackground(new java.awt.Color(204, 0, 0));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveChange, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreatePeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbMovieID1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOnShowing)
                            .addComponent(lbMovieID3)
                            .addComponent(lbMovieDescription))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(onShowingTrue)
                            .addComponent(commingTrue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(commingFalse)
                            .addComponent(onShowingFalse)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbMovieID)
                            .addGap(49, 49, 49)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMovieName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMovieForm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOfTables, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOfTables, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMovieForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMovieID))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMovieID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbOnShowing)
                    .addComponent(onShowingTrue)
                    .addComponent(onShowingFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMovieID3)
                    .addComponent(commingTrue)
                    .addComponent(commingFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMovieDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMovieIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieIDKeyReleased
        // TODO add your handling code here:
        if (txtMovieID.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMovieIDKeyReleased

    private void txtMovieNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieNameKeyTyped
        // TODO add your handling code here:
        if (txtMovieName.getText().length() >= 80) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMovieNameKeyTyped

    private void txtDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyTyped
        // TODO add your handling code here:
        if (txtDescription.getText().length() >= 80) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescriptionKeyTyped

    private void btnMovieFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieFormActionPerformed
        // TODO add your handling code here:
        MovieController control = new MovieController();
        control.showMovieFormDB();
        this.dispose();
    }//GEN-LAST:event_btnMovieFormActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        HomePageController backHome = new HomePageController();
        backHome.loadHomePage();
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDeletePeriodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeletePeriodActionPerformed
        // TODO add your handling code here:
        MovieController control = new MovieController();
        control.setMovieDetailForm(this);
        control.showDeletePeriodForm(Integer.valueOf(txtMovieID.getText()));
    }// GEN-LAST:event_btnDeletePeriodActionPerformed

    private void txtMovieIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMovieIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMovieIDActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_formKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }// GEN-LAST:event_formKeyTyped

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setEnable(true);
        btnSaveChange.setEnabled(true);
        btnEdit.setEnabled(false);

    }// GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setEnable(false);
        btnSaveChange.setEnabled(false);
        btnEdit.setEnabled(true);

    }// GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveChangeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveChangeActionPerformed
        // TODO add your handling code here:
        if (txtMovieName.getText().equals("") || txtDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!");
        } else {
            MovieController control = new MovieController();
            control.setMovieDetailForm(this);
            Movie movie = new Movie();
            movie.setMovie_id(Integer.parseInt(txtMovieID.getText()));
            movie.setMovie_name(txtMovieName.getText());
            movie.setDescription(txtDescription.getText());
            movie.setOnShowing(onShowingTrue.isSelected());
            movie.setCommingSoon(commingTrue.isSelected());
            control.updateMovieDetail(movie);
        }
        this.Cancel();

    }// GEN-LAST:event_btnSaveChangeActionPerformed

    private void btnCreatePeriodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreatePeriodActionPerformed
        // TODO add your handling code here:
        MovieController control = new MovieController();
        control.setMovieDetailForm(this);
        control.showAddPeriodForm(Integer.valueOf(txtMovieID.getText()));
    }// GEN-LAST:event_btnCreatePeriodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MovieController control = new MovieController();
        this.FormClose();
        control.showMovieFormDB();

    }// GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreatePeriod;
    private javax.swing.JButton btnDeletePeriod;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGrCommingSoon;
    private javax.swing.ButtonGroup btnGrOnShow;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMovieForm;
    private javax.swing.JButton btnSaveChange;
    private javax.swing.JRadioButton commingFalse;
    private javax.swing.JRadioButton commingTrue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMovieDescription;
    private javax.swing.JLabel lbMovieID;
    private javax.swing.JLabel lbMovieID1;
    private javax.swing.JLabel lbMovieID3;
    private javax.swing.JLabel lbOfTables;
    private javax.swing.JLabel lbOnShowing;
    private javax.swing.JRadioButton onShowingFalse;
    private javax.swing.JRadioButton onShowingTrue;
    private javax.swing.JTable tbPeriods;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtMovieName;
    // End of variables declaration//GEN-END:variables
}
