/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngthtrong.theatermanager.views;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ngthtrong.theatermanager.controller.MoiveController;
import ngthtrong.theatermanager.models.Movie;
import ngthtrong.theatermanager.models.Period;

/**
 *
 * @author jhiny
 */
public class MovieDetailForm extends javax.swing.JFrame {

    /**
     * Creates new form MovieFrom
     */
    public MovieDetailForm() {
        initComponents();
    }

    public void FormLoad() {
        this.setVisible(true);
        setEnable(false);
    }

    public void FormClose() {
        this.setVisible(false);
    }

    public void Cancel() {
        btnEdit.setEnabled(true);
        btnSaveChange.setEnabled(false);
        setEnable(false);
    }

    public void setEnable(boolean enable) {
        txtDescription.setEnabled(enable);
        txtMovieName.setEnabled(enable);
        commingFalse.setEnabled(enable);
        commingTrue.setEnabled(enable);
    }

    public void SetBtnDeleteEnable(boolean enable) {
        btnDeletePeriod.setEnabled(enable);
    }

    public void SetDetailMovie(Movie movie) {
        txtMovieID.setText(String.valueOf(movie.getMovie_id()));
        txtMovieName.setText(movie.getMovie_name());
        txtDescription.setText(movie.getDescription());
        onShowingTrue.setSelected(movie.isOnShowing());
        onShowingFalse.setSelected(!movie.isOnShowing());
        commingTrue.setSelected(movie.isCommingSoon());
        commingFalse.setSelected(!movie.isCommingSoon());
    }

    public void SetPeriods(List<Period> periods) {
        if (periods == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tbPeriods.getModel();
        model.setRowCount(0);
        for (Period period : periods) {
            model.addRow(
                    new Object[]{String.valueOf(period.getPeriod_id()), period.getMovie_name(), period.getTheater_name(),
                        period.getPeriod_time(), period.getPeriod_date()});
        }
        tbPeriods.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrOnShow = new javax.swing.ButtonGroup();
        btnGrCommingSoon = new javax.swing.ButtonGroup();
        btnUserForm = new javax.swing.JButton();
        btnMovieForm = new javax.swing.JButton();
        btnTheaterForm = new javax.swing.JButton();
        lbMovieID = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        lbMovieID1 = new javax.swing.JLabel();
        txtMovieName = new javax.swing.JTextField();
        lbMovieDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnSaveChange = new javax.swing.JButton();
        btnDeletePeriod = new javax.swing.JButton();
        btnCreatePeriod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPeriods = new javax.swing.JTable();
        onShowingTrue = new javax.swing.JRadioButton();
        onShowingFalse = new javax.swing.JRadioButton();
        lbOnShowing = new javax.swing.JLabel();
        lbMovieID3 = new javax.swing.JLabel();
        commingTrue = new javax.swing.JRadioButton();
        commingFalse = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUserForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm.setText("User");

        btnMovieForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMovieForm.setText("Movie");

        btnTheaterForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTheaterForm.setText("Theater");

        lbMovieID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID.setText("Movie ID:");

        txtMovieID.setEnabled(false);

        lbMovieID1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID1.setText("Name:");

        lbMovieDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSaveChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveChange.setText("Save change");
        btnSaveChange.setEnabled(false);
        btnSaveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangeActionPerformed(evt);
            }
        });

        btnDeletePeriod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePeriod.setText("Delete Period");
        btnDeletePeriod.setEnabled(false);
        btnDeletePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeriodActionPerformed(evt);
            }
        });

        btnCreatePeriod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreatePeriod.setText("Add Period");
        btnCreatePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePeriodActionPerformed(evt);
            }
        });

        tbPeriods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Period ID", "Movie Name", "Theater", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbPeriods);
        if (tbPeriods.getColumnModel().getColumnCount() > 0) {
            tbPeriods.getColumnModel().getColumn(1).setResizable(false);
            tbPeriods.getColumnModel().getColumn(2).setResizable(false);
            tbPeriods.getColumnModel().getColumn(3).setResizable(false);
        }

        btnGrOnShow.add(onShowingTrue);
        onShowingTrue.setText("Yes");
        onShowingTrue.setEnabled(false);

        btnGrOnShow.add(onShowingFalse);
        onShowingFalse.setText("No");
        onShowingFalse.setEnabled(false);

        lbOnShowing.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbOnShowing.setText("Now Showing:");

        lbMovieID3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID3.setText("Comming Soon:");

        btnGrCommingSoon.add(commingTrue);
        commingTrue.setText("Yes");

        btnGrCommingSoon.add(commingFalse);
        commingFalse.setText("No");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveChange, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreatePeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbMovieID1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOnShowing)
                            .addComponent(lbMovieID3)
                            .addComponent(lbMovieDescription))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(commingTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(commingFalse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(onShowingTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(onShowingFalse))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbMovieID)
                            .addGap(49, 49, 49)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMovieName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUserForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMovieForm)
                        .addGap(18, 18, 18)
                        .addComponent(btnTheaterForm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovieForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheaterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovieID)
                    .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMovieID1)
                    .addComponent(txtMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOnShowing)
                    .addComponent(onShowingTrue)
                    .addComponent(onShowingFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commingFalse)
                    .addComponent(commingTrue)
                    .addComponent(lbMovieID3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMovieDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePeriodActionPerformed
        // TODO add your handling code here:
        MoiveController control = new MoiveController();
        control.setMovieDetailForm(this);
        control.showDeletePeriodForm(Integer.valueOf(txtMovieID.getText()));
    }//GEN-LAST:event_btnDeletePeriodActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setEnable(true);
        btnSaveChange.setEnabled(true);
        btnEdit.setEnabled(false);

    }// GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setEnable(false);
        btnSaveChange.setEnabled(false);
        btnEdit.setEnabled(true);

    }// GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveChangeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveChangeActionPerformed
        // TODO add your handling code here:
        MoiveController control = new MoiveController();
        control.setMovieDetailForm(this);
        Movie movie = new Movie();
        movie.setMovie_id(Integer.parseInt(txtMovieID.getText()));
        movie.setMovie_name(txtMovieName.getText());
        movie.setDescription(txtDescription.getText());
        movie.setOnShowing(onShowingTrue.isSelected());
        movie.setCommingSoon(commingTrue.isSelected());
        control.updateMovieDetail(movie);
        this.Cancel();

    }// GEN-LAST:event_btnSaveChangeActionPerformed

    private void btnCreatePeriodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreatePeriodActionPerformed
        // TODO add your handling code here:
        MoiveController control = new MoiveController();
        control.setMovieDetailForm(this);
        control.showAddPeriodForm(Integer.valueOf(txtMovieID.getText()));
    }// GEN-LAST:event_btnCreatePeriodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MoiveController control = new MoiveController();
        this.FormClose();
        control.showMovieFormDB();

    }// GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDetailForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDetailForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDetailForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDetailForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDetailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreatePeriod;
    private javax.swing.JButton btnDeletePeriod;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGrCommingSoon;
    private javax.swing.ButtonGroup btnGrOnShow;
    private javax.swing.JButton btnMovieForm;
    private javax.swing.JButton btnSaveChange;
    private javax.swing.JButton btnTheaterForm;
    private javax.swing.JButton btnUserForm;
    private javax.swing.JRadioButton commingFalse;
    private javax.swing.JRadioButton commingTrue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMovieDescription;
    private javax.swing.JLabel lbMovieID;
    private javax.swing.JLabel lbMovieID1;
    private javax.swing.JLabel lbMovieID3;
    private javax.swing.JLabel lbOnShowing;
    private javax.swing.JRadioButton onShowingFalse;
    private javax.swing.JRadioButton onShowingTrue;
    private javax.swing.JTable tbPeriods;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtMovieName;
    // End of variables declaration//GEN-END:variables
}
