/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngthtrong.theatermanager.views;

import java.awt.Color;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;

import ngthtrong.theatermanager.controller.HomePageController;
import ngthtrong.theatermanager.controller.UserController;
import ngthtrong.theatermanager.dao.UserDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS PC
 */
public class UserBookingForm extends javax.swing.JFrame {

    /**
     * Creates new form UserBookingForm
     */
    private int user_id;

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public UserBookingForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1000, 630);
        this.setTitle("Add booking by User");
    getContentPane().setBackground(Color.getHSBColor(0.2f, 0.05f, 0.95f));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBtn = new javax.swing.JButton();
        AmoutLabel = new javax.swing.JLabel();
        bookIdLabel = new javax.swing.JLabel();
        BookIdText = new javax.swing.JTextField();
        amountText = new javax.swing.JTextField();
        backToUserBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfBookingTable = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Booking ");

        userBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userBtn.setText("User");

        AmoutLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AmoutLabel.setText("Amount");

        bookIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookIdLabel.setText("Book id");

        BookIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BookIdTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BookIdTextKeyTyped(evt);
            }
        });

        amountText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        amountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountTextKeyTyped(evt);
            }
        });

        backToUserBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backToUserBtn.setText("Back to user");
        backToUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToUserBtnActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("List of booking");

        listOfBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie", "Theater", "Capacity", "Booked", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listOfBookingTable);

        btnHome.setBackground(new java.awt.Color(204, 0, 0));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(BookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AmoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnHome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(backToUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addGap(460, 460, 460))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AmoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backToUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToUserBtnActionPerformed
        UserController uc = new UserController();
        this.bookFromDispose();
        uc.detailsFormLoad(user_id);
    }//GEN-LAST:event_backToUserBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        UserController uc = new UserController();
        int periodId = Integer.parseInt(BookIdText.getText());
        int periodAmount = Integer.parseInt(amountText.getText());
        int recentPeriod = uc.getPeriodSize(periodId);
        int recentCapacity = uc.getTheaterCapacity(periodId);

        if (!uc.checkPeriodIdExist(periodId)) {
            JOptionPane.showMessageDialog(rootPane, "Id is not exist!");
        } else {
            if ((periodAmount + recentPeriod) > recentCapacity || periodAmount <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Amount incorrect !");
            }else{
                uc.addBooking(periodId, user_id, recentCapacity);
                uc.updatePeriodSize(periodId, periodAmount);
                JOptionPane.showMessageDialog(rootPane, "Added !");
            }
        }
        addBtn.setEnabled(true);
        setTableDefauth();
    }//GEN-LAST:event_addBtnActionPerformed

    private void BookIdTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BookIdTextKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_BookIdTextKeyTyped

    private void amountTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyTyped
        char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_amountTextKeyTyped

    private void BookIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BookIdTextKeyReleased
        if ("".equals(BookIdText.getText()) || "".equals(amountText.getText())) {
            addBtn.setEnabled(false);
        } else {
            addBtn.setEnabled(true);
        }
         char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
    }//GEN-LAST:event_BookIdTextKeyReleased

    private void amountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextKeyReleased
        if ("".equals(amountText.getText()) || "".equals(BookIdText.getText())) {
            addBtn.setEnabled(false);
        } else {
            addBtn.setEnabled(true);
        }
         char test = evt.getKeyChar();
        if (!Character.isDigit(test)) {
            evt.consume();
        }
        String getLength = amountText.getText();
        if(getLength.length() > 6){
            evt.consume();
        }
    }//GEN-LAST:event_amountTextKeyReleased

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        HomePageController backHome = new HomePageController();
        backHome.loadHomePage();
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    public void setTableDefauth() {
        UserController uc = new UserController();
        List<Object[]> list = uc.getBookingForBookForm();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Movie");
        dtm.addColumn("Theater");
        dtm.addColumn("Capacity");
        dtm.addColumn("Booked");
        dtm.addColumn("Time");
        dtm.addColumn("Date");
        for (Object[] oj : list) {
            dtm.addRow(oj);
        }
        listOfBookingTable.setModel(dtm);
    }

    public void bookFromViews() {
        this.setVisible(true);
        addBtn.setEnabled(false);
        setTableDefauth();
    }

    public void bookFromDispose() {
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserBookingForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmoutLabel;
    private javax.swing.JTextField BookIdText;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField amountText;
    private javax.swing.JButton backToUserBtn;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listOfBookingTable;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
