/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngthtrong.theatermanager.views.MoiveForms;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ngthtrong.theatermanager.controller.MoiveController;
import ngthtrong.theatermanager.models.Movie;

/**
 *
 * @author jhiny
 */
public class MovieForm extends javax.swing.JFrame {

    /**
     * Creates new form MovieFrom
     */
    public MovieForm() {
        initComponents();
    }

    public void FormLoad() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieForm().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrOnShow = new javax.swing.ButtonGroup();
        btnGrCommingSoon = new javax.swing.ButtonGroup();
        lbTitle = new javax.swing.JLabel();
        btnUserForm = new javax.swing.JButton();
        btnMovieForm = new javax.swing.JButton();
        btnTheaterForm = new javax.swing.JButton();
        lbMovieID = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        lbMovieID1 = new javax.swing.JLabel();
        txtMovieName = new javax.swing.JTextField();
        onShowTrue = new javax.swing.JRadioButton();
        lbMovieOnShow = new javax.swing.JLabel();
        onShowFalse = new javax.swing.JRadioButton();
        lbMovieCommingSoon = new javax.swing.JLabel();
        commingTrue = new javax.swing.JRadioButton();
        commingFalse = new javax.swing.JRadioButton();
        lbMovieDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnUserForm1 = new javax.swing.JButton();
        btnUserForm2 = new javax.swing.JButton();
        btnUserForm3 = new javax.swing.JButton();
        btnUserForm4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAllMovies = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitle.setText("Manager:");

        btnUserForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm.setText("User");
        btnUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserFormActionPerformed(evt);
            }
        });

        btnMovieForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMovieForm.setText("Movie");
        btnMovieForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieFormActionPerformed(evt);
            }
        });

        btnTheaterForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTheaterForm.setText("Theater");
        btnTheaterForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheaterFormFormActionPerformed(evt);
            }
        });

        lbMovieID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID.setText("Movie ID:");

        lbMovieID1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieID1.setText("Name:");

        txtMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieNameActionPerformed(evt);
            }
        });

        btnGrOnShow.add(onShowTrue);
        onShowTrue.setText("Yes");
        onShowTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onShowTrueActionPerformed(evt);
            }
        });

        lbMovieOnShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieOnShow.setText("On show:");

        btnGrOnShow.add(onShowFalse);
        onShowFalse.setText("No");
        onShowFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onShowFalseActionPerformed(evt);
            }
        });

        lbMovieCommingSoon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieCommingSoon.setText("Comming soon:");

        btnGrCommingSoon.add(commingTrue);
        commingTrue.setText("Yes");
        commingTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commingTrueActionPerformed(evt);
            }
        });

        btnGrCommingSoon.add(commingFalse);
        commingFalse.setText("No");
        commingFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commingFalseActionPerformed(evt);
            }
        });

        lbMovieDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMovieDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnUserForm1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm1.setText("Add");
        btnUserForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserForm1ActionPerformed(evt);
            }
        });

        btnUserForm2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm2.setText("Save");
        btnUserForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserForm2ActionPerformed(evt);
            }
        });

        btnUserForm3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm3.setText("Delete by ID");
        btnUserForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserForm3ActionPerformed(evt);
            }
        });

        btnUserForm4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserForm4.setText("Get Detail by ID");
        btnUserForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserForm4ActionPerformed(evt);
            }
        });

        tbAllMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Movie ID", "Name", "On show", "Comming soon", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbAllMovies);
        if (tbAllMovies.getColumnModel().getColumnCount() > 0) {
            tbAllMovies.getColumnModel().getColumn(0).setResizable(false);
            tbAllMovies.getColumnModel().getColumn(2).setResizable(false);
            tbAllMovies.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbMovieDescription)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbMovieCommingSoon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(commingTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(commingFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMovieID)
                                .addComponent(lbMovieID1)
                                .addComponent(lbMovieOnShow))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(onShowTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(onShowFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(txtMovieID))
                                    .addComponent(txtMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUserForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUserForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnUserForm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUserForm4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMovieForm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTheaterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovieForm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTheaterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMovieID)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMovieID1)
                            .addComponent(txtMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMovieOnShow)
                            .addComponent(onShowTrue)
                            .addComponent(onShowFalse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMovieCommingSoon)
                            .addComponent(commingTrue)
                            .addComponent(commingFalse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMovieDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUserForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserForm3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUserForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserForm4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserFormActionPerformed

    private void btnMovieFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovieFormActionPerformed

    private void btnTheaterFormFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheaterFormFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTheaterFormFormActionPerformed

    private void txtMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieNameActionPerformed

    private void onShowTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onShowTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onShowTrueActionPerformed

    private void onShowFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onShowFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onShowFalseActionPerformed

    private void commingTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commingTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commingTrueActionPerformed

    private void commingFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commingFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commingFalseActionPerformed

    private void btnUserForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserForm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserForm1ActionPerformed

    private void btnUserForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserForm2ActionPerformed
        // TODO add your handling code here:
        Movie movie = new Movie();
        movie.setMovie_name(txtMovieName.getText());
        movie.setDescription(txtDescription.getText());
        if (onShowTrue.isSelected()) {
            movie.setOnShowing(true);
        } else {
            movie.setOnShowing(false);
        }
        if (commingTrue.isSelected()) {
            movie.setCommingSoon(true);
        } else {
            movie.setCommingSoon(false);
        }
        MoiveController control = new MoiveController();
        control.addMovieToDB(movie, this);
        
    }//GEN-LAST:event_btnUserForm2ActionPerformed

    private void btnUserForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserForm3ActionPerformed
        // TODO add your handling code here:
        int id = Integer.valueOf(txtMovieID.getText());
        MoiveController control = new MoiveController();
        control.deleteMovieInDB(id, this);
        
    }//GEN-LAST:event_btnUserForm3ActionPerformed

    private void btnUserForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserForm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserForm4ActionPerformed

    public void setMovies(List<Movie> Movies) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Movie ID");
        model.addColumn("Name");
        model.addColumn("On Show");
        model.addColumn("Comming Soon");
        model.addColumn("Description");
        for (Movie movie : Movies) {
            model.addRow(new Object[]{
                movie.getMovie_id(),
                movie.getMovie_name(),
                movie.isOnShowing(),
                movie.isCommingSoon(),
                movie.getDescription()
            });
        }
        tbAllMovies.setModel(model);
    }

    public void setMovieById(Movie movie) {
        txtMovieID.setText(String.valueOf(movie.getMovie_id()));
        txtMovieName.setText(movie.getMovie_name());
        if (movie.isOnShowing()) {
            onShowFalse.setSelected(true);
        } else {
            onShowTrue.setSelected(true);
        }
        if (movie.isCommingSoon()) {
            commingFalse.setSelected(true);
        } else {
            commingTrue.setSelected(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrCommingSoon;
    private javax.swing.ButtonGroup btnGrOnShow;
    private javax.swing.JButton btnMovieForm;
    private javax.swing.JButton btnTheaterForm;
    private javax.swing.JButton btnUserForm;
    private javax.swing.JButton btnUserForm1;
    private javax.swing.JButton btnUserForm2;
    private javax.swing.JButton btnUserForm3;
    private javax.swing.JButton btnUserForm4;
    private javax.swing.JRadioButton commingFalse;
    private javax.swing.JRadioButton commingTrue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMovieCommingSoon;
    private javax.swing.JLabel lbMovieDescription;
    private javax.swing.JLabel lbMovieID;
    private javax.swing.JLabel lbMovieID1;
    private javax.swing.JLabel lbMovieOnShow;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JRadioButton onShowFalse;
    private javax.swing.JRadioButton onShowTrue;
    private javax.swing.JTable tbAllMovies;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtMovieName;
    // End of variables declaration//GEN-END:variables
}
